config/routes.rb
Rails.application.routes.draw do

  
	# set root
	root 		'static_pages#home'
	
	# static_pages routes
  get 		'/home'			,to: 		'static_pages#home'
  get 		'/about'		,to: 		'static_pages#about'
  get 		'/contact'	,to: 		'static_pages#contact'
  get 		'/other'		,to: 		'static_pages#other'
  get 		'/privacy'	,to: 		'static_pages#privacy'
  # devise routes
 
  devise_for :users ,:controllers => { registrations: 'users/registrations', :omniauth_callbacks => "users/omniauth_callbacks", sessions: 'users/sessions' } 
  devise_scope :user do
   	get 		'/login'		,to:	 	'users/sessions#new'				#,as: 'new_user_session'
  	# post 		'/login'		,to: 	'devise/sessions#create'		,as: :user_session
  	delete 	'/logout'		=>	 	'users/sessions#destroy'		#,as: :destroy_user_session
    get 		'/signup' 	=> 		'devise/registrations#new'	#,as: 'new_user_registration' # custom path to sign_up/registration
  end

  # routes for users profiles
  resources :users ,:only => [:show] do
  	member do
      get :following ,:followers
    end
  end
  
  get 	'/search'			,to: 		'users#search'
  get 	'/find'				,to: 		'users#find_friends'

  # routes for relationship model
  resources 	:relationships,	only: [:create, :destroy]

  # routes for store
  get 		'/store'		,to: 		'stores#index'
  post		'/store'		,to: 		'stores#buy'

  # routes for game
  get 		'/settings'	,to: 		'games#settings'
  post 		'/settings'	,to: 		'games#change_settings'
  get 		'/game'			,to:  	'games#game'
  post 		'/game' 		,to: 		'games#get_score'

  # routes for notifications
  resources :notifications ,:only => [:show]

  #router for game_master and game_founder
  get   '/masterpanel'  ,to:    'game_masters#index'
  get   '/founderpanel' ,to:    'game_founders#index'

  #for game_founder
  post  '/fban'         ,to:    'game_founders#ban'
  post  '/removeban'    ,to:    'game_founders#remove'
  post  '/approveban'   ,to:    'game_founders#approve'
  post  '/promote'      ,to:    'game_founders#promote'
  post  '/demote'       ,to:    'game_founders#demote'

  #for game_master
  post  '/mban'         ,to:    'game_masters#ban'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



end

app/models/user.rb
class User < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :twitter]  
  validates :name, presence: true
  validates :last_name, presence: true
  validates :nickname, presence: true
  validates :nickname, uniqueness: true, if: -> {self.nickname.present?}

  # Relationship model
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy

  has_many :following, through: :active_relationships, source: :followed

	has_many :passive_relationships, class_name:  "Relationship",
                                 foreign_key: "followed_id",
                                 dependent:   :destroy

  has_many :followers, through: :passive_relationships

  # Game Data model
  has_one :game_datum, dependent:   :destroy

  # Score model
  has_many :scores, dependent:   :destroy

  # Shop model
  has_many :shops, dependent:   :destroy

  has_many :items, through: :shops, dependent:   :destroy

  # Notifications model
  has_many :notifications, foreign_key: :dest_id

  # Profile image
  validates_integrity_of  :avatar
  
  validates_processing_of :avatar

  # Follows a user.
  def follow(other_user)
    following << other_user
  end

  # Unfollows a user.
  def unfollow(other_user)
    following.delete(other_user)
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

  # Search tools
  def self.search(search)
  	where("nickname LIKE ? ", "%#{search}%") 
	end

	# Omniauth login/sign up Facebook/Twitter
	def self.create_from_facebook_omniauth(params)
		user = User.find_by(email: params.info.email)
		user = User.find_by(uid: params.uid) if user.nil?
		if user.nil?
			pass = 'NardomenFriendlyPassword'
			user = User.create!( name: params.info.first_name,
														last_name: params.info.last_name,
														nickname: 'Guest'+Random.rand(100000).to_s,
														email: params.info.email,
														password: pass,
														password_confirmation: pass)
			user.set_default_data
		end
    user.update({
      token: params.credentials.token,
      provider: params.provider,
      uid: params.uid
    }) 
    user
  end

  def self.create_from_twitter_omniauth(params)
		user = User.find_by(email: params.info.email)
		user = User.find_by(uid: params.uid) if user.nil?
		if user.nil?
			pass = 'NardomenFriendlyPassword'
			complete_name = params.info.name
			name = complete_name.split
			user = User.create!( name: name[0],
														last_name: name[1],
														nickname: 'Guest'+Random.rand(100000).to_s,
														email: params.info.email,
														password: pass,
														password_confirmation: pass)
			user.set_default_data
		end
    user.update({
      token: params.credentials.token,
      provider: params.provider,
      uid: params.uid
    }) 
    user
  end

	# Returns a user's status feed.
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Score.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

  # Return user's level
  def level
  	game_datum.level
  end

  # Return user's money
  def money
  	game_datum.money
  end

  def exp
  	game_datum.exp
  end

  # Return user's best score
  def best_score
  	scores.max_by(&:score).score
  end

  # Returns first 5 notifications
  def notif
  	notifications.first(5)
  end

  # Has item?
  def has_item?(item)
  	items.include?(item)
  end

  # user can buy item?
  def can_buy?(item)
  	level >= item.level && money >= item.price
  end

  # Return active skin
  def skin
  	game_datum.skin
  end

  # Return active enemy
  def enemy
  	game_datum.enemy
  end

  # Return active sword
  def sword
  	game_datum.sword
  end

  # Return active landscape
  def landscape
  	game_datum.landscape
  end

  # Return purchased skins
  def skins
  	items.where(category: "skin")
  end

  # Return purchased enemies
  def enemies
  	items.where(category: "enemy")
  end

  # Return purchased swords
  def swords
  	items.where(category: "sword")
  end

  # Return purchased landscapes
  def landscapes
  	items.where(category: "landscape")
  end

  # Change active skin
  def change_skin(new_skin)
  	game_datum.update_attribute(:skin, new_skin)
  end

  # Change active skin
  def change_enemy(new_enemy)
  	game_datum.update_attribute(:enemy, new_enemy)
  end

  # Change active skin
  def change_sword(new_sword)
  	game_datum.update_attribute(:sword, new_sword)
  end

  # Change active skin
  def change_landscape(new_landscape)
  	game_datum.update_attribute(:landscape, new_landscape)
  end

  # Set default items and data at sign up
  def set_default_data
  	skin = Item.default_skin
    enemy = Item.default_enemy
    sword = Item.default_sword
    landscape = Item.default_landscape
    create_game_datum(money: 50, level: 1, exp: 0, skin: skin, enemy: enemy, sword: sword, landscape: landscape ) 
    items << skin
    items << enemy
    items << sword
    items << landscape
    update({
      token: nil,
      provider: nil,
      uid: nil
    	}) 
	end


	# destroy items and data when user cancel the account
	def destroy_user
		user_shops = shops
  	user_scores = scores
  	user_shops.each do |shop|
  		shop.destroy
  	end
  	user_scores.each do |score|
  		score.destroy
  	end
  	game_datum.destroy
	end
	
	# Private functions
	private
  
    def avatar_size_validation
      errors[:avatar] << "should be less than 500KB" if avatar.size > 0.5.megabytes
    end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def facebook
    @user = User.create_from_facebook_omniauth(omniauth_params)
    if @user.persisted?
    	if User.all.include?(@user)
	  		ban = Ban.find_by(user: @user)
	  		if Ban.all.include?(ban)
	  			if ban.day_ban > 500.years.from_now
	  				redirect_to '/login', :notice => "You are banned permanently. Good Bye!"
	  				return
	  			elsif ban.day_ban > DateTime.now.in_time_zone
	  				redirect_to '/login', :notice => "You are banned until #{ban.day_ban}"
	  				return
	  			else
	  				ban.destroy
	  			end
	  		end
	  	end
    	sign_in @user, event: :authentication 
    	if @user.created_at > 3.minutes.ago
    		redirect_to edit_user_registration_path(@user), :notice => 		"Sign up successfully.\nYour Nardomen account is linked with Facebook.\n
    																																	Change your nickname and your password (current: NardomenFriendlyPassword )\n
    																																	This password should be know by other user so it strongly recommended to change it!!"
    	else
    		redirect_to root_path, :notice => 		"Log in successfully.\nYour Nardomen account is linked with Facebook."
    	end
    end
  end

  def twitter
    @user = User.create_from_twitter_omniauth(omniauth_params)
    if @user.persisted?
    	if User.all.include?(@user)
	  		ban = Ban.find_by(user: @user)
	  		if Ban.all.include?(ban)
	  			if ban.day_ban > 500.years.from_now
	  				redirect_to '/login', :notice => "You are banned permanently. Good Bye!"
	  				return
	  			elsif ban.day_ban > DateTime.now.in_time_zone
	  				redirect_to '/login', :notice => "You are banned until #{ban.day_ban}"
	  				return
	  			else
	  				ban.destroy
	  			end
	  		end
	  	end
    	sign_in @user, event: :authentication 
    	if @user.created_at > 3.minutes.ago
    		redirect_to edit_user_registration_path(@user), :notice => 		"Sign up successfully.\nYour Nardomen account is linked with Twitter.\n
    																																	Change your nickname and your password (current: NardomenFriendlyPassword ).
    																																	This password should be know by other user so it strongly recommended to change it!!"
    	else
    		redirect_to root_path, :notice => 		"Log in successfully.\nYour Nardomen account is linked with Twitter."
    	end
    end
  end
  
  private
  def omniauth_params
    request.env["omniauth.auth"]
  end

end

app/controllers/users/registrations_controller.rb
       # frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    current_user.set_default_data unless current_user.nil?
    
  end

  # GET /resource/edit
  # def edit
  #   super             
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super   
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
  	user_info = params[:user]
  	user = User.find_by(email: user_info[:email])
  	if User.all.include?(user)
  		ban = Ban.find_by(user: user)
  		if Ban.all.include?(ban)
  			if ban.day_ban > 500.years.from_now
  				redirect_to '/login', :notice => "You are banned permanently. Good Bye!"
  				return
  			elsif ban.day_ban > DateTime.now.in_time_zone
  				redirect_to '/login', :notice => "You are banned until #{ban.day_ban}"
  				return
  			else
  				ban.destroy
  			end
  		end
  	end
    super
    current_user.update({ token: '', provider: '', uid: ''})
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
require 'koala'

class UsersController < ApplicationController
	before_action :authenticate_user!

	def show
		@user = User.find(params[:id])
		@scores = @user.scores.paginate(page: params[:page])
	end

	def index
	end

	def search
		@users = nil
  	if params[:nick]
  		if params[:nick] == ''
  			@users = nil
  		else
    		@users = User.search(params[:nick]).order(:nickname.downcase)
    	end
    else
    	redirect_to root_path
    end
	end

	def find_friends
		@user = current_user
		if @user.provider == "facebook"
			@oauth = Koala::Facebook::OAuth.new('445360272621130', ENV['FB_SECRET_KEY'])
			@graph = Koala::Facebook::API.new(@user.token)
			@friends_list = @graph.get_connections('me' , "friends")
			@friends = Array.new
			@friends_list.each do |friend|
				@friends << User.find_by(uid: friend['id'])
			end
		end
	end

	def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

end

app/helpers/users_helper.rb
module UsersHelper

	def current_user?(user)
		current_user == user
	end

end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <%= hidden_field_tag :followed_id, @user.id %>
  <%= f.submit "Follow", class: "follow btn btn-labeled btn-info" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_game_data.html.erb
<div class="gamedata">
	Level: <%= @user.level %> <br/>
	<% if current_user?(@user) %>
		Money: <%= @user.money %> <br/>
	<% end %> 
	Best score: 
	<% if @user.scores.any? %>
		<%= @user.best_score %> <br/>
		Total scores: <%= @user.scores.count %>
	<% else %>
		0
		Total scores: 0
	<% end %> <br>
	Exp: <%= @user.exp %>
	<br>
</div>

app/views/users/_profile_sharing.html.erb
<!--
<span>
    
        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
        <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
        <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
    



    <p class="social-share-button" data-title="Hey! 
        Look at my profile! Hurry up and join me at Nardomen! 
        " data-img="" data-url="http://localhost:3000/users/1" data-desc="" data-via="">
        <a rel="nofollow " data-site="facebook" class="ssb-icon ssb-facebook fa fa-facebook" onclick="return SocialShareButton.share(this);" title="Share to Facebook" href="#"></a>

        <a rel="nofollow " data-site="twitter" class="ssb-icon ssb-twitter fa fa-twitter" onclick="return SocialShareButton.share(this);" title="Share to Twitter" href="#"></a>            
    </p>
</span>
-->

<span>
    <ul>
        <%= content_tag :li, class: "social-share-button", :"data-title"=> "Look at my profile! Hurry up and join me at Nardomen!", :"data-img" => "", :"data-url" => user_url(current_user), :"data-desc"=>"", :"data-via"=>"" do %> 

            <%= link_to '#' , class: "ssb-icon ssb-facebook", :onclick => "return SocialShareButton.share(this);", :title => "Share to Facebook" , :"data-site" => "facebook" , :rel => "nofollow" do %>

                <i class="fa fa-facebook" aria-hidden="true"></i>

            <% end %> <!-- </a> -->
        <% end %> <!-- </li> -->

        <%= content_tag :li, class: "social-share-button", :"data-title"=> "Look at my profile! Hurry up and join me at Nardomen!", :"data-img" => "", :"data-url" => user_url(current_user), :"data-desc"=>"", :"data-via"=>"" do %> 

            <%= link_to '#' , class: "ssb-icon ssb-twitter", :onclick => "return SocialShareButton.share(this);", :title => "Share to Twitter" , :"data-site" => "twitter" , :rel => "nofollow" do %>

                    <i class="fa fa-twitter" aria-hidden="true"></i>
            <% end %> <!-- </a> -->
        <% end %><!-- </li> -->

    </ul>

</span>

app/views/users/_search_form.html.erb
<li class = "align-bottom">
	<%= form_tag(search_path, method: :get, class: 'search-form') do %>
	  		Search user by nickname:  <%= text_field_tag  :nick %>
	  		<%= submit_tag 'Search' ,name: 'search_commit' , class: 'search-submit'%>
	<% end %>
</li>

<!-- Search form 
<form class="form-inline md-form form-sm">
    <input class="form-control form-control-sm mr-3 w-75" type="text" placeholder="Search" aria-label="Search">
    <i class="fa fa-search" aria-hidden="true"></i>
</form>

-->

app/views/users/_search_list.html.erb
<% if !@users.blank? && params[:nick] != '' %>
	<span> Result for " <%= "#{params[:nick]}" %> " : </span>
	<ul class = 'search-list'>
		<%= render @users %>
	</ul>
	<%= @users = nil %>
<% elsif params[:nick] == '' %>
	<span> Please provide a nickname </span>
	<ul class = 'search-list'> </ul>
<% elsif  params[:nick] %>
	<div class="noresult">
		<span> No result to display for "<%= "#{params[:nick]}" %>"</span>
		<ul class = 'search-list'> </ul>
	</div>
<% end %>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    Following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    Followers
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "unfollow btn btn-labeled btn-info" %>
<% end %>

app/views/users/_user.html.erb
<% if Ban.find_by(user: user).nil? %>
	<li class = 'user-list-elem'>
	  	<%= link_to user.nickname, user , class: 'user-link linkbello' %>
	  	<% if (current_user.gm? || current_user.gf?) && !user.gf? && !current_user?(user)%>
	  		<br>
	  		<%  if current_user.gf? %>
	  			<%= form_tag("/fban",method:"post") do %>
	  				<%= hidden_field_tag(:user, user.id, class: 'founder-ban-form') %>
		  			<div class="alert alert-info">
			  			<strong> Info: </strong> Ban an user<br>
			  			<%= label_tag :days%>
		            	<%= number_field_tag :days, nil, { :min => 0, class:"form-control founder-days-ban #{user.id}-days", autofocus: true, id:"#{user.id}-days" } %>
			 			<%= label_tag 'Permanent ban?'%>
			  			<%= check_box_tag :permanent, nil, false, class:"custom-control-label founder-ban-perm #{user.id}-perm", id: user.id.to_s+'-permanent' %>
			  			<%= submit_tag "Ban", class:"btn btn-primary btn-smfounder-ban-submit #{user.id}-ban-submit" , name: 'commit-ban'+user.id.to_s  %>
		  			</div>
		  		<% end %>
		  		<% if !user.gm? %>
			  		<%= form_tag("/promote",method:"post") do %>
			  			<%= hidden_field_tag(:user, user.id) %>
			  			<div class="alert alert-warning">
		  					<strong> Warning: </strong> Promote an user is an error bro <span class="glyphicon glyphicon-thumbs-down"></span><br>
			  				<%= submit_tag "Promote to GM ",class:"btn btn-warning btn-sm #{user.id}-promote", name: 'promote'+user.id.to_s %>
			  			</div>

			  		<% end %>
				<% else %>
					<%= form_tag("/demote",method:"post") do %>
			  			<%= hidden_field_tag(:user, user.id) %>
			  			<div class="alert alert-info">
			  				<strong> Info: </strong> If you want you can demote <span class="glyphicon glyphicon-thumbs-up"></span><br>
			  			<%= submit_tag "Demote as a Gamer",class:"btn btn-primary btn-sm #{user.id}-demote", name: 'demote'+user.id.to_s %>
			  			</div>
			  		<% end %>
				<% end %>

	  		<% elsif %>
	  			<%= form_tag("/mban",method:"post", class: 'master-ban-form') do %>
			  		<%= hidden_field_tag(:user, user.id) %>
			  		<div class="alert alert-warning">
			  			<strong>Warning: </strong> if you are in this page, you know what you do <br>
				  		<%= label_tag :days %>
				  		<%= number_field_tag :days, nil, { :min => 0, class:"form-control master-days-ban #{user.id}-days", autofocus: true } %>
				  		<%= label_tag 'Send a request for permanent ban'%>
				  		<%= check_box_tag :request , nil, false, class:"custom-control-label master-ban-request #{user.id}-req" %>
				  		<%= submit_tag "Ban", class:"btn btn-warning btn-smmaster-ban-submit #{user.id}-ban-submit" %>
				  	</div>
		  		<%  end %>
			<%  end %>
	  	<% end %>  
	  	<hr>
	</li>
<% end %>

app/views/users/find_friends.html.erb
<section class = 'fb-friends-section'>
	<% if @friends.empty? %>
		<span class = 'fb-friends-mess'> No Facebook friends to show </span>
	<% else %>
		<span class = 'fb-friends-mess'> Here a list of your facebook friends using Nardomen: </span>
		<ul class = 'fb-friends-list'>
			<%= render @friends %>
		</ul> 
	<% end %>
</section>

app/views/users/search.html.erb
<%= provide :title,  "Search"%>
<div class = 'users-list result spaziosearch'>
	<%= render 'search_list' %>
<hr>
	<p class="text-right">
		<small>
			<small>
				search powered by Rahios <span> &copy; </span>
			</small>
		</small>
	</p>
</div>

app/views/users/show.html.erb
<%= provide :title, @user.nickname %>
<div class="text-center">
    <h2 id="nameuser"> <%= @user.nickname %> 's Profile </h2>
</div>

<div class="card">
    <div class="box">
        <div class = 'img'>
            <%= image_tag(@user.avatar.url, size: "300",class:"img-thumbnail rounded mx-auto d-block")%> 
        </div>
        <h2> <%= @user.nickname %> <br> 
            <span>
                <%if @user.gf? %>
                    Game Founder
                <%elsif @user.gm? %>
                    Game Master
                <%else %>
                    Gamer
                <% end %>
            </span>
        </h2>
        <%= render 'follow_form' if user_signed_in? %>
        <p> <%= render 'stats' %> </p>
        <hr id="breakline">
        <% if current_user?(@user) %>
            <%= render 'profile_sharing' %>
        <% end %>
        <%= render 'game_data' %>

    </div>
</div>

<div class="text-center">
    <br><br><br><br><br>
    <br><br><br><br><br>        
    <br><br><br><br><br>
    <br><br><br><br><br> 
    <br><br><br><br><br>
    <br><br><br><br><br> 
           
    
    <% if current_user?(@user) || current_user.following?(@user) || current_user.gm? || current_user.gf? %>
        <section class = 'user-scores gamedata'>
            <ul class = 'user-scores-list list-unstyled'>
                <%= render @scores %>
            </ul>
            <%= will_paginate @scores %>
        </section>  
    <% else %>
        <br><br><br><br><br>
        <br><br><br><br><br> 
    <% end %>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>

<div class="row">
  <aside class="col-md-4">
    
    <section class="user_info">
      <h1><%= @user.nickname %></h1>
      <span><%= link_to "view my profile", @user %></span>
    </section>
    
    <section class="stats">
      <%= render 'stats' %>
    </section>

  </aside>
  
  <div class="col-md-8">
    <h3><%= @title %></h3>
    
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  
  </div>

</div>